version: "3"

services:
  node:
    # image: node:13-stretch
    image: node:lts-slim
    working_dir: "/app"
    volumes:
      - .:/app

  frontend:
    # image: node:13-stretch
    image: node:lts-slim
    working_dir: "/app/packages/frontend"
    command: yarn dev
    user: "${UID}:${GID}"
    ports:
      - 5000:5000
      - 35729:35729
    volumes:
      - .:/app

  backend:
    # image: node:13-stretch
    image: node:lts-slim
    working_dir: "/app/packages/backend"
    user: "${UID}:${GID}"
    environment:
      - PORT=4000
      #- REDIS=redis
      #- REDIS=132.163.53.82
    command: yarn dev
    #ports:
      #- 4000:4000
    volumes:
      - .:/app
    network_mode: host

